// Generated by CoffeeScript 1.7.1
(function() {
  var dgram;

  dgram = require('dgram');

  module.exports = function(incomingMessageFromDevice, rinfo) {
    var outgoingAckMsg, sock;
    outgoingAckMsg = Buffer.concat([new Buffer([0xFF]), incomingMessageFromDevice.slice(8, 10)]);
    sock = dgram.createSocket('udp4');
    sock.bind(2013);
    return sock.send(outgoingAckMsg, 0, outgoingAckMsg.length, rinfo.port, rinfo.address, function(err, bytes) {
      return sock.close();
    });
  };

}).call(this);
