// Generated by CoffeeScript 1.7.1
(function() {
  var ack, log, parse;

  ack = require('./ack');

  log = require('./log');

  parse = {
    '0': require('./msg-type-0'),
    '2': require('./msg-type-2'),
    '4': require('./msg-type-4'),
    '5': require('./msg-type-5')
  };

  module.exports = function(msg, rinfo) {
    var e, logObject, reading;
    try {
      reading = {
        serviceType: msg.readUInt8(0),
        msgType: msg.readUInt8(1),
        macAddress: msg.slice(2, 8).toString('hex').toUpperCase(),
        sequenceNumber: msg.readUInt16BE(8),
        updateTime: msg.readUInt32BE(10) * 1000,
        rssi: msg.readInt8(14)
      };
      if (typeof parse["" + reading.msgType] === 'function') {
        parse["" + reading.msgType](msg, reading);
      }
      if (process.env.NODE_ENV === 'test') {
        return reading;
      } else {
        log.info(reading, "SUCCESS parsing " + rinfo.size + " bytes from " + rinfo.address);
        return ack(msg, rinfo);
      }
    } catch (_error) {
      e = _error;
      logObject = {
        err: {
          message: e.message,
          name: e.name,
          stack: e.stack
        },
        hex: msg.toString('hex'),
        text: msg.toString()
      };
      if (process.env.NODE_ENV === 'test') {
        return logObject;
      } else {
        return log.error(logObject, "ERROR parsing " + rinfo.size + " bytes from " + rinfo.address);
      }
    }
  };

}).call(this);
