// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(msg, reading) {
    var idx, sensorHubData, _i, _ref, _results;
    reading.sensorHubType = msg.readUInt8(16);
    reading.numberOfSensors = msg.readUInt8(17);
    reading.sensorHubBattery = msg.readUInt8(18);
    reading.sensorHubRssi = msg.readInt8(19);
    reading.sensorHubMacAddress = msg.slice(21, 27).toString('hex').match(/\w{2}/g).reverse().join('').toUpperCase();
    reading.offsetOfSigned = msg.slice(27, 28)[0].toString(2);
    sensorHubData = msg.slice(28);
    _results = [];
    for (idx = _i = 0, _ref = reading.numberOfSensors; 0 <= _ref ? _i < _ref : _i > _ref; idx = 0 <= _ref ? ++_i : --_i) {
      _results.push(reading["sensorHubData" + (idx + 1)] = sensorHubData.readInt16LE(idx * 2));
    }
    return _results;
  };

}).call(this);
