// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(msg, reading) {
    reading.gatewayBattery = msg.readUInt8(16);
    return reading.gatewayEventCode = msg.readUInt8(17);
  };

}).call(this);
