// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(msg, reading) {
    reading.sensorHubBattery = msg.readUInt8(16);
    reading.sensorHubRssi = msg.readInt8(17);
    reading.sensorHubMacAddress = msg.slice(19, 25).toString('hex').toUpperCase();
    reading.sensorEventStart = msg.readUInt8(25);
    return reading.sensorEventEnd = msg.readUInt8(26);
  };

}).call(this);
